# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               ê¸°ë¡í•˜ëŠ” ê³µê°„
tagline:             ""
description:         ""
url:                 https://seon54.github.io
baseurl:             https://seon54.github.io
paginate:            5
sass:
  style: compressed
  sass_dir: _scss 

# About/contact
author:
  name:              ìŠ¤ë…•
  description:       ëŠë ¤ë„ ë©ˆì¶”ì§€ ì•ŠëŠ” ê±°ë¶ì´ğŸ¢
  contact:               
    github:          https://github.com/seon54 
    email:           mailto:seonhyeongpark54@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  About:          
    - '/about/'
  Category:           
    - '/category/'
    - { JavaScript: '/category/#javascript' }
    - { Node.js: '/category/#nodejs' }
    - { Python: '/category/#python' }
    - { Network: '/category/#network' }
    - { Tool: '/category/#tool' }  
    - { í›„ê¸°: '/category/#review' }  
    
  Tags:
    - '/tags/'

disqus_short_name: 'seon54'

# Custom vars
version:             1.0.0
